name: simple-ml-demo
channels:
  - https://repo.anaconda.com/pkgs/snowflake
dependencies:
  - python=3.11
  - ipykernel
  - matplotlib==3.7.2
  - seaborn==0.12.2
  - snowflake-ml-python==1.3.0
  - snowflake-snowpark-python[pandas]==1.14.0
  - scikit-learn==1.3.0
  - xgboost==1.7.6
  - python-dotenv
  - pip:
    - snowflake==0.5.1