name: app_environment
channels:
  - snowflake
dependencies:
  - matplotlib=3.8.4
  - networkx=3.2.1
  - seaborn=0.13.2
  - snowflake-ml-python=1.6.1
  - snowflake-snowpark-python=1.20.0
  - snowflake.core=0.12.1
  - tabulate=0.9.0