name: app_environment
channels:
  - snowflake
dependencies:
  - matplotlib=3.8.4
  - networkx=3.2.1
  - seaborn=0.13.2
  - snowflake-ml-python=1.5.3
  - snowflake-snowpark-python=1.18.0
  - snowflake.core=0.9.0
  - tabulate=0.9.0