name: simple-ml-demo
channels:
  - https://repo.anaconda.com/pkgs/snowflake
dependencies:
  - python=3.11
  - ipykernel
  - matplotlib==3.8.4
  - seaborn==0.12.2
  - snowflake-ml-python==1.5.0
  - snowflake-snowpark-python[pandas]==1.16.0
  - scikit-learn==1.3.0
  - xgboost==1.7.6
  - python-dotenv
  - snowflake==0.8.0